# Generated by Django 5.0.3 on 2024-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_sharedcalendar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedcalendar',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
